language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test --verbose --all
  - cargo build --verbose --all
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then cargo doc; fi
after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then sh scripts/travis-doc-upload.sh; fi
cache: cargo
matrix:
  allow_failures:
    - rust: nightly