language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test --verbose --all
  - cargo build --verbose --all
  - cargo doc
after_success: sh scripts/travis-doc-upload.sh
cache: cargo
matrix:
  allow_failures:
    - rust: nightly