[package]
name = "tini"
description = "A tiny ini parsing library"
version = "1.3.0"
authors = ["Alexey Golubev <dr.freecx@gmail.com>", "Vova Abdrakhmanov <369565@gmail.com>"]
documentation = "https://docs.rs/tini"
repository = "https://github.com/pinecrew/tini"
keywords = ["ini", "configuration", "conf", "cfg"]
license = "BSD-3-Clause"
include = ["src/*.rs", "Cargo.toml", "README.md"]
edition = "2021"

[lib]
name = "tini"
